/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8049030();
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int
// argc, char **ubp_av, void (*init)(void), void (*fini)(void), void
// (*rtld_fini)(void), void *stack_end); ssize_t read(int fd, void *buf, size_t
// nbytes); int printf(const char *format, ...);
// __sighandler_t signal(int sig, __sighandler_t handler);
// unsigned int alarm(unsigned int seconds);
// int puts(const char *s);
// int system(const char *command);
// void exit(int status);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int __isoc99_scanf(const char *, ...); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void sub_804911D();
void dl_relocate_static_pie();
void _x86_get_pc_thunk_bx();
FILE **deregister_tm_clones();
int register_tm_clones();
FILE **_do_global_dtors_aux();
int frame_dummy();
unsigned int alarm(unsigned int seconds);
void init();  // idb
void __cdecl view_account(unsigned __int8 *account, int idx);
void print_menu();  // idb
void print_flag();  // idb
int __cdecl main(int argc, const char **argv, const char **envp);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*dword_804C008)(void) = NULL;  // weak
FILE *_bss_start;                   // idb
FILE *stdout;                       // idb
char completed_0;                   // weak
// extern _UNKNOWN _gmon_start__; weak

//----- (08049000) --------------------------------------------------------
void *init_proc() {
    void *result;  // eax

    result = &_gmon_start__;
    if (&_gmon_start__) return (void *)((int (*)(void))_gmon_start__)();
    return result;
}

//----- (08049030) --------------------------------------------------------
int sub_8049030() { return dword_804C008(); }
// 804C008: using guessed type int (*dword_804C008)(void);

//----- (080490F0) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1 @<eax>, void (*a2)(void) @<edx>) {
    int v2;         // esi
    int v3;         // [esp-4h] [ebp-4h] BYREF
    char *retaddr;  // [esp+0h] [ebp+0h] BYREF

    v2 = v3;
    v3 = a1;
    __libc_start_main((int(__cdecl *)(int, char **, char **))main, v2, &retaddr,
                      0, 0, a2, &v3);
    __halt();
}
// 80490F7: positive sp value 4 has been found

//----- (0804911D) --------------------------------------------------------
void sub_804911D() { ; }

//----- (08049130) --------------------------------------------------------
void dl_relocate_static_pie() { ; }

//----- (08049140) --------------------------------------------------------
void _x86_get_pc_thunk_bx() { ; }

//----- (08049150) --------------------------------------------------------
FILE **deregister_tm_clones() { return &_bss_start; }
// 8049150: could not find valid save-restore pair for ebp

//----- (08049190) --------------------------------------------------------
int register_tm_clones() { return 0; }
// 8049190: could not find valid save-restore pair for ebp

//----- (080491D0) --------------------------------------------------------
FILE **_do_global_dtors_aux() {
    FILE **result;  // eax

    if (!completed_0) {
        result = deregister_tm_clones();
        completed_0 = 1;
    }
    return result;
}
// 80491D0: could not find valid save-restore pair for ebp
// 804C048: using guessed type char completed_0;

//----- (08049200) --------------------------------------------------------
int frame_dummy() { return register_tm_clones(); }

//----- (08049206) --------------------------------------------------------
unsigned int __noreturn alarm(unsigned int seconds) {
    puts("TIME OUT");
    exit(-1);
}

//----- (0804921D) --------------------------------------------------------
void init() {
    setvbuf(_bss_start, 0, 2, 0);
    setvbuf(stdout, 0, 2, 0);
    signal(14, (__sighandler_t)alarm);
    alarm(0x1Eu);
    puts("=====================================");
    puts("=                                   =");
    puts("=       Subway Account System       =");
    puts("=                                   =");
    puts("=====================================");
}

//----- (080492A5) --------------------------------------------------------
void __cdecl view_account(unsigned __int8 *account, int idx) {
    printf("Index %d : %02x\n", idx, account[idx]);
}

//----- (080492CA) --------------------------------------------------------
void print_menu() {
    puts("[F]ill account info");
    puts("[V]iew account info");
    puts("[E]xit");
    printf("> ");
}

//----- (08049304) --------------------------------------------------------
void print_flag() { system("cat ./flag"); }

//----- (08049317) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp) {
    int idx;                      // [esp+4h] [ebp-90h] BYREF
    int name_len;                 // [esp+8h] [ebp-8Ch] BYREF
    char choice[2];               // [esp+Eh] [ebp-86h] BYREF
    unsigned __int8 account[64];  // [esp+10h] [ebp-84h] BYREF
    char name[64];                // [esp+50h] [ebp-44h] BYREF
    unsigned int v9;              // [esp+90h] [ebp-4h]

    v9 = __readgsdword(0x14u);
    memset(account, 0, sizeof(account));
    memset(name, 0, sizeof(name));
    *(_WORD *)choice = 0;
    idx = 0;
    name_len = 0;
    init();
    while (1) {
        while (1) {
            while (1) {
                print_menu();
                read(0, choice, 2u);
                if (choice[0] != 70) break;
                printf("Data : ");
                read(0, account, 0x40u);
            }
            if (choice[0] != 86) break;
            printf("Index : ");
            __isoc99_scanf("%d", &idx);
            view_account(account, idx);
        }
        if (choice[0] == 69) break;
        puts("Invalid choice");
    }
    printf("Name Size : ");
    __isoc99_scanf("%d", &name_len);
    printf("Name : ");
    read(0, name, name_len);
    return 0;
}
// 80490E0: using guessed type int __isoc99_scanf(const char *, ...);

//----- (08049540) --------------------------------------------------------
void term_proc() { ; }

// nfuncs=39 queued=17 decompiled=17 lumina nreq=0 worse=0 better=0
// ALL OK, 17 function(s) have been successfully decompiled
